import "@/styles/main.scss";

import { routing } from "@/i18n/routing";
import { ReactQueryProvider } from "@/providers/QueryClientProvider";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Inter } from "next/font/google";
import { notFound } from "next/navigation";

const inter = Inter({
    weight: ["400", "600"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Profile Manager",
    description: "Generated by create next app",
};

export async function generateStaticParams() {
    return [{ lang: "en" }, { lang: "pt-BR" }];
}

export default async function LocaleLayout({
    children,
    params,
}: {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}) {
    const { locale } = await params;

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    if (!routing.locales.includes(locale as any)) {
        notFound();
    }

    const messages = await getMessages();

    return (
        <html lang={locale}>
            <body className={inter.className}>
                <ReactQueryProvider>
                    <NextIntlClientProvider messages={messages}>
                        {children}
                    </NextIntlClientProvider>
                </ReactQueryProvider>
            </body>
        </html>
    );
}
